import re

filepath = 'src/pages/index.astro'

with open(filepath, 'r') as f:
    content = f.read()

essay = """<section class="chapter" id="database">
    <div class="chapter-label">Chapter 05</div>
    <h1>Intensive Deep Dive: Compile-Time SQL & WAL Durability</h1>

    <h2>1. The Fallacy of Object-Relational Mappers (ORMs)</h2>
    <p>In standard application development (Ruby on Rails, Django, or Node.js Prisma), developers interface with the database using an Object-Relational Mapper (ORM). ORMs abstract away SQL entirely, allowing developers to query the database using chaining methods like <code>User.find().where(status="active")</code>. This abstraction is a primary cause of catastrophic database failures in production.</p>
    <p>ORMs inevitably generate highly sub-optimal SQL queries. They frequently trigger the N+1 query problem, fetch massive amounts of unneeded columns (<code>SELECT *</code>), and fail to utilize database-specific features like partial indexes or JSONB operators. More dangerously, the query generated by an ORM is only evaluated at <strong>runtime</strong>. If the ORM generates invalid SQL, the compiler will not catch it; the application will simply panic in production when the query is executed.</p>

    <h2>2. Compile-Time AST Verification via `sqlx`</h2>
    <p>To operate at the absolute highest level of engineering, we abandon ORMs and write raw SQL using the <code>sqlx</code> crate. However, <code>sqlx</code> is not merely a database driver; it is a compile-time verification engine.</p>
    <p>When you use the <code>sqlx::query!</code> macro in Rust, the macro intercepts the compilation process. During compilation, <code>sqlx</code> physically opens a TCP connection to a live Postgres database running on your local machine (or in a Docker container). It sends the raw SQL query to the Postgres server and asks Postgres to generate a query execution plan using the <code>PREPARE</code> statement.</p>
    
    <div class="code-block"><div class="code-header"><span class="code-filename">src/infrastructure/postgres.rs</span><span class="code-lang">rust</span></div>
    <pre><span class="kw">use</span> <span class="type">sqlx</span>::<span class="type">PgPool</span>;
<span class="kw">use</span> <span class="type">uuid</span>::<span class="type">Uuid</span>;

<span class="kw">pub struct</span> <span class="type">User</span> {
    <span class="kw">pub</span> id: <span class="type">Uuid</span>,
    <span class="kw">pub</span> email: <span class="type">String</span>,
    <span class="kw">pub</span> is_active: <span class="type">bool</span>,
}

<span class="kw">pub async fn</span> <span class="fn">fetch_active_user</span>(pool: &amp;<span class="type">PgPool</span>, user_id: <span class="type">Uuid</span>) -&gt; <span class="type">Result</span>&lt;<span class="type">User</span>, <span class="type">sqlx</span>::<span class="type">Error</span>&gt; {
    <span class="cmt">// This macro executes at COMPILE TIME. </span>
    <span class="cmt">// If 'is_active' is misspelled as 'is_activ', or if 'user_id' is the wrong type,</span>
    <span class="cmt">// the Rust compiler will instantly fail the build.</span>
    <span class="kw">let</span> user = <span class="mac">sqlx::query_as!</span>(
        <span class="type">User</span>,
        <span class="str">r#"
        SELECT id, email, is_active
        FROM users
        WHERE id = $1 AND is_active = true
        "#</span>,
        user_id
    )
    .<span class="fn">fetch_one</span>(pool)
    .<span class="kw">await</span>?;

    <span class="type">Ok</span>(user)
}</pre></div>

    <p>Postgres analyzes the Abstract Syntax Tree (AST) of the SQL query. It checks the database schema to ensure the table <code>users</code> exists, verifies that the <code>email</code> column is indeed of type <code>VARCHAR</code>, and confirms that the provided bind parameter <code>$1</code> matches the <code>UUID</code> type. Postgres then returns this metadata back to the Rust compiler. The Rust compiler uses this metadata to statically type-check the output of the query against your <code>User</code> struct. If there is a single typo, or a type mismatch, the Rust compiler fails the build. You mathematically cannot ship an invalid SQL query to production.</p>

    <h2>3. The Physics of the Write-Ahead Log (WAL)</h2>
    <p>When you execute an <code>INSERT</code> statement in Postgres, you assume the data is written directly to the hard drive table file (the heap). This is entirely false. Hard drives (especially HDDs, but also SSDs) are block devices. Writing small, random pieces of data to various locations on a disk is incredibly slow.</p>
    <p>To achieve high transaction throughput, Postgres utilizes a <strong>Write-Ahead Log (WAL)</strong>. When an <code>INSERT</code> occurs, Postgres does not touch the actual table on disk. Instead, it modifies a cached version of the table in RAM (the <code>shared_buffers</code>). Simultaneously, it appends a sequential log entry describing the change to the end of the WAL file on disk.</p>
    
    <h3>3.1 The `fsync` System Call</h3>
    <p>To guarantee durability (the 'D' in ACID), Postgres must ensure the WAL entry is physically magnetized onto the disk platters (or stored in the SSD flash cells) before returning a success message to your Rust application. It does this by issuing an <code>fsync</code> system call to the Linux kernel. <code>fsync</code> halts execution until the disk hardware explicitly confirms the flush. Because WAL writes are purely sequential, <code>fsync</code> is extremely fast.</p>
    <p>If the server loses power, the RAM <code>shared_buffers</code> are erased, and the table data on disk remains outdated. However, upon reboot, Postgres reads the WAL file sequentially from the last checkpoint, mathematically "replaying" the transactions back into RAM to instantly recover the lost state.</p>

    <h2>4. The Connection Pooling Crisis & PgBouncer</h2>
    <p>In a hyper-scale architecture, the Rust application (running on Tokio) might spawn thousands of concurrent tasks. If each task attempts to open a direct TCP connection to Postgres, the database will crash. Postgres operates using a Process-Per-Connection model (not a thread-per-connection model). Every single TCP connection requires Postgres to fork a massive OS process, consuming ~10MB of RAM. 5,000 connections will instantly consume 50GB of RAM just for connection overhead.</p>

    <h3>4.1 Transaction-Level Pooling</h3>
    <p>We solve this using <strong>PgBouncer</strong>, a lightweight middleware proxy written in C. We configure our Rust <code>sqlx::PgPool</code> (which maintains maybe 20 connections) to connect to PgBouncer. PgBouncer then maintains a very small, highly optimized pool of actual connections to Postgres (e.g., 50 connections).</p>
    <p>Crucially, PgBouncer is configured in <strong>Transaction Mode</strong>. When Rust Task A sends a <code>BEGIN</code> statement, PgBouncer assigns it one of the 50 Postgres connections. The instant Rust Task A sends <code>COMMIT</code>, PgBouncer ruthlessly yanks the Postgres connection away and assigns it to Rust Task B. Because transactions only take a few milliseconds, a pool of 50 backend Postgres connections can easily multiplex and serve 10,000 concurrent Rust clients, mathematically preventing database memory exhaustion.</p>
</section>"""

pattern = r'<section class="chapter" id="database">.*?</section>'
content = re.sub(pattern, essay, content, flags=re.DOTALL)

with open(filepath, 'w') as f:
    f.write(content)

print("Intensive Deep Essay expansion applied to Chapter 05.")
