import re

filepath = 'src/pages/index.astro'

new_chapter = """<section class="chapter" id="async-internals">
    <div class="chapter-label">Chapter 22</div>
    <h1>Expert Architecture: Async Internals, Pin & GATs</h1>
    <p>To write hyper-optimized, production-grade Rust, you cannot treat <code>async/await</code> as magic. You must understand the underlying state machines generated by the compiler. In this chapter, we explore how <code>Future</code> works, why <code>Pin</code> is strictly necessary for self-referential memory, and how <strong>Generic Associated Types (GATs)</strong> unlock zero-copy streaming.</p>

    <h2>The Future Trait & State Machines</h2>
    <p>When you write an <code>async fn</code>, the Rust compiler does not execute it immediately. Instead, it desugars your code into an anonymous enum representing a state machine that implements the <code>Future</code> trait.</p>
    
    <div class="code-block">
      <div class="code-header"><span class="code-filename">std::future::Future</span><span class="code-lang">rust</span></div>
      <pre><span class="kw">pub trait</span> <span class="type">Future</span> {
    <span class="kw">type</span> Output;
    <span class="kw">fn</span> <span class="fn">poll</span>(<span class="kw">self</span>: <span class="type">Pin</span>&lt;&amp;<span class="kw">mut Self</span>&gt;, cx: &amp;<span class="kw">mut</span> <span class="type">Context</span>&lt;<span class="lifetime">'_</span>&gt;) -&gt; <span class="type">Poll</span>&lt;<span class="kw">Self</span>::Output&gt;;
}</pre>
    </div>
    <p>The <code>Context</code> provides access to a <code>Waker</code>, which tells the executor (like Tokio) exactly when to wake up this specific task after it returns <code>Poll::Pending</code>.</p>

    <h2>Self-Referential Structs & The Pin Contract</h2>
    <p>Why does the <code>poll</code> method take <code>Pin&lt;&amp;mut Self&gt;</code> instead of a standard mutable reference <code>&amp;mut self</code>? The answer lies in self-referential structs.</p>
    <p>An <code>async</code> block often holds references to local variables across <code>.await</code> yield points. When compiled into a state machine enum, this means the struct holds a pointer to its own fields. If this struct were moved in memory, the internal pointer would immediately become invalid, causing Undefined Behavior.</p>
    
    <div class="callout warning">
      <div class="callout-title">The Danger of Memory Moves</div>
      <p>Rust's default behavior allows any type to be moved in memory. <code>Pin</code> acts as a compiler-enforced contract that guarantees the memory location of the data will <strong>never change</strong> until it is dropped, rendering it safe for the async state machine to hold internal pointers.</p>
    </div>

    <h2>Manual Future Implementation</h2>
    <p>To truly grasp this, let's implement a delay future completely from scratch, utilizing the Waker API directly.</p>

    <div class="code-block">
      <div class="code-header"><span class="code-filename">src/core/delay.rs</span><span class="code-lang">rust</span></div>
      <pre><span class="kw">use</span> <span class="type">std</span>::<span class="type">future</span>::<span class="type">Future</span>;
<span class="kw">use</span> <span class="type">std</span>::<span class="type">pin</span>::<span class="type">Pin</span>;
<span class="kw">use</span> <span class="type">std</span>::<span class="type">task</span>::{<span class="type">Context</span>, <span class="type">Poll</span>};
<span class="kw">use</span> <span class="type">std</span>::<span class="type">time</span>::<span class="type">Instant</span>;

<span class="kw">pub struct</span> <span class="type">Delay</span> {
    when: <span class="type">Instant</span>,
}

<span class="kw">impl</span> <span class="type">Future</span> <span class="kw">for</span> <span class="type">Delay</span> {
    <span class="kw">type</span> Output = ();

    <span class="kw">fn</span> <span class="fn">poll</span>(<span class="kw">self</span>: <span class="type">Pin</span>&lt;&amp;<span class="kw">mut Self</span>&gt;, cx: &amp;<span class="kw">mut</span> <span class="type">Context</span>&lt;<span class="lifetime">'_</span>&gt;) -&gt; <span class="type">Poll</span>&lt;<span class="kw">Self</span>::Output&gt; {
        <span class="kw">if</span> <span class="type">Instant</span>::<span class="fn">now</span>() &gt;= <span class="kw">self</span>.when {
            <span class="type">Poll</span>::Ready(())
        } <span class="kw">else</span> {
            <span class="cmt">// Clone the waker and spawn a thread to wake it up later</span>
            <span class="kw">let</span> waker = cx.<span class="fn">waker</span>().<span class="fn">clone</span>();
            <span class="kw">let</span> when = <span class="kw">self</span>.when;
            
            <span class="type">std</span>::<span class="type">thread</span>::<span class="fn">spawn</span>(<span class="kw">move</span> || {
                <span class="kw">while</span> <span class="type">Instant</span>::<span class="fn">now</span>() &lt; when {
                    <span class="type">std</span>::<span class="type">thread</span>::<span class="fn">sleep</span>(<span class="type">std</span>::<span class="type">time</span>::<span class="type">Duration</span>::<span class="fn">from_millis</span>(<span class="num">10</span>));
                }
                waker.<span class="fn">wake</span>();
            });
            
            <span class="type">Poll</span>::Pending
        }
    }
}</pre>
    </div>

    <h2>Generic Associated Types (GATs)</h2>
    <p>With Rust 1.65, <strong>Generic Associated Types (GATs)</strong> landed in stable Rust. GATs allow traits to have associated types that contain their own generic lifetimes, enabling patterns that were previously impossible, like zero-copy streaming of deserialized data chunks.</p>
    
    <div class="code-block">
      <div class="code-header"><span class="code-filename">src/core/streaming.rs</span><span class="code-lang">rust</span></div>
      <pre><span class="kw">trait</span> <span class="type">ZeroCopyStream</span> {
    <span class="cmt">// The associated Item type borrows from the stream itself</span>
    <span class="kw">type</span> Item&lt;<span class="lifetime">'a</span>&gt; <span class="kw">where</span> <span class="kw">Self</span>: <span class="lifetime">'a</span>;
    
    <span class="kw">fn</span> <span class="fn">next</span>(&amp;<span class="kw">mut self</span>) -&gt; <span class="type">Option</span>&lt;<span class="kw">Self</span>::Item&lt;<span class="lifetime">'_</span>&gt;&gt;;
}

<span class="kw">struct</span> <span class="type">PacketParser</span> {
    buffer: <span class="type">Vec</span>&lt;<span class="type">u8</span>&gt;,
}

<span class="kw">impl</span> <span class="type">ZeroCopyStream</span> <span class="kw">for</span> <span class="type">PacketParser</span> {
    <span class="kw">type</span> Item&lt;<span class="lifetime">'a</span>&gt; = &amp;<span class="lifetime">'a</span> [<span class="type">u8</span>];

    <span class="kw">fn</span> <span class="fn">next</span>(&amp;<span class="kw">mut self</span>) -&gt; <span class="type">Option</span>&lt;<span class="kw">Self</span>::Item&lt;<span class="lifetime">'_</span>&gt;&gt; {
        <span class="kw">if</span> <span class="kw">self</span>.buffer.<span class="fn">is_empty</span>() {
            <span class="type">None</span>
        } <span class="kw">else</span> {
            <span class="type">Some</span>(&amp;<span class="kw">self</span>.buffer[..])
        }
    }
}</pre>
    </div>
    <p>By defining <code>Item&lt;'a&gt;</code>, the <code>PacketParser</code> can yield slices of its internal buffer directly to the caller, requiring zero allocations per packet. In an API serving millions of requests per second, this completely bypasses the memory allocator, resulting in massive throughput gains.</p>

</section>"""

with open(filepath, 'r') as f:
    content = f.read()

# Replace the section block for async-internals
pattern = r'<section class="chapter" id="async-internals">.*?</section>'
content = re.sub(pattern, new_chapter, content, flags=re.DOTALL)

with open(filepath, 'w') as f:
    f.write(content)

print("Chapter 22 expanded successfully.")
