import re

filepath = 'src/pages/index.astro'

new_chapter = """<section class="chapter" id="workers">
    <div class="chapter-label">Chapter 12</div>
    <h1>Expert Architecture: Distributed Background Workers</h1>

    <p>Sending a newsletter to 10,000 subscribers blocks the HTTP request for several minutes. This is unacceptable. We must enqueue these tasks for a background worker. However, a naive Postgres <code>SKIP LOCKED</code> queue will quickly succumb to lock contention at scale. To achieve <strong>Exactly-Once Delivery</strong> at hyperscale, we use the <strong>Transactional Outbox Pattern</strong> combined with <strong>Distributed Redis Streams</strong>.</p>

    <h2>The Transactional Outbox Pattern & Idempotency</h2>
    <p>If we write the newsletter to Postgres, but our API crashes before pushing the task to Redis, the data is permanently out of sync. The Outbox Pattern solves this by saving the "intent to send" inside the <em>exact same</em> Postgres transaction as the newsletter save.</p>
    
    <div class="code-block">
      <div class="code-header">
        <span class="code-filename">src/routes/newsletters.rs</span>
        <span class="code-lang">rust</span>
      </div>
      <pre><span class="kw">pub async fn</span> <span class="fn">publish_newsletter</span>(
    <span class="type">Form</span>(form): <span class="type">Form</span>&lt;<span class="type">PublishForm</span>&gt;,
    <span class="type">State</span>(state): <span class="type">State</span>&lt;<span class="type">AppState</span>&gt;,
    <span class="cmt">// UUID generated by the client to prevent duplicate submissions on retry</span>
    <span class="type">Header</span>(idempotency_key): <span class="type">Header</span>&lt;<span class="str">"X-Idempotency-Key"</span>&gt;,
) -&gt; <span class="kw">impl</span> IntoResponse {
    <span class="kw">let</span> <span class="kw">mut</span> transaction = state.db.begin().<span class="kw">await</span>?;

    <span class="cmt">// 1. Idempotency Check: Did we already process this exact UUID?</span>
    <span class="kw">if let</span> <span class="type">Some</span>(saved_response) = get_saved_response(idempotency_key, &amp;<span class="kw">mut</span> transaction).<span class="kw">await</span>? {
        <span class="kw">return</span> saved_response;
    }

    <span class="cmt">// 2. Save newsletter content</span>
    <span class="kw">let</span> issue_id = insert_newsletter_issue(&amp;<span class="kw">mut</span> transaction, &amp;form).<span class="kw">await</span>?;

    <span class="cmt">// 3. Save to OUTBOX table in the SAME transaction</span>
    enqueue_to_outbox(&amp;<span class="kw">mut</span> transaction, issue_id).<span class="kw">await</span>?;
    transaction.commit().<span class="kw">await</span>?;

    <span class="cmt">// A separate background Relay process will read the Outbox table and push to Redis,</span>
    <span class="cmt">// ensuring 100% guarantee of delivery even if the API pod instantly dies here.</span>
    <span class="type">Redirect</span>::to(<span class="str">"/admin/newsletters"</span>)
}</pre>
    </div>

    <h2>Distributed Redis Streams & Consumer Groups</h2>
    <p>Once the Relay pushes the task to a Redis Stream, we leverage <strong>Consumer Groups</strong>. Redis tracks which specific worker pod took which job. The job remains in a "Pending" (PEL) state until the worker explicitly issues an <code>XACK</code> (Acknowledge) command.</p>

    <div class="code-block">
      <div class="code-header">
        <span class="code-filename">src/worker.rs</span>
        <span class="code-lang">rust</span>
      </div>
      <pre><span class="kw">use</span> <span class="type">redis</span>::<span class="type">AsyncCommands</span>;
<span class="kw">use</span> <span class="type">redis</span>::<span class="type">streams</span>::{<span class="type">StreamReadOptions</span>, <span class="type">StreamReadReply</span>};

<span class="kw">pub async fn</span> <span class="fn">worker_loop</span>(redis_client: <span class="type">redis</span>::<span class="type">Client</span>, email_client: <span class="type">EmailClient</span>) {
    <span class="kw">let</span> <span class="kw">mut</span> con = redis_client.get_async_connection().<span class="kw">await</span>.unwrap();
    <span class="kw">let</span> opts = <span class="type">StreamReadOptions</span>::default().group(<span class="str">"newsletter_group"</span>, <span class="str">"worker-pod-1"</span>).block(<span class="num">5000</span>);

    <span class="kw">loop</span> {
        <span class="cmt">// XREADGROUP: Read 1 new job, automatically putting it into Pending (PEL) for this pod</span>
        <span class="kw">let</span> reply: <span class="type">StreamReadReply</span> = con.xread_options(&amp;[<span class="str">"newsletter_stream"</span>], &amp;[<span class="str">"&gt;"</span>], &amp;opts).<span class="kw">await</span>.unwrap();
        
        <span class="kw">for</span> key <span class="kw">in</span> reply.keys {
            <span class="kw">for</span> id <span class="kw">in</span> key.ids {
                <span class="kw">let</span> issue_id: <span class="type">String</span> = id.map.get(<span class="str">"issue_id"</span>).unwrap().clone();
                <span class="kw">let</span> email: <span class="type">String</span> = id.map.get(<span class="str">"email"</span>).unwrap().clone();

                <span class="cmt">// Execute the heavy task</span>
                <span class="kw">match</span> email_client.send_email(&amp;email, &amp;issue_id).<span class="kw">await</span> {
                    <span class="type">Ok</span>(_) =&gt; {
                        <span class="cmt">// XACK: We succeeded! Tell Redis to permanently remove it from the stream</span>
                        <span class="kw">let</span> _: () = con.xack(<span class="str">"newsletter_stream"</span>, <span class="str">"newsletter_group"</span>, &amp;[id.id]).<span class="kw">await</span>.unwrap();
                    }
                    <span class="type">Err</span>(e) =&gt; {
                        <span class="mac">tracing::error!</span>(<span class="str">"Delivery failed: {:?}"</span>, e);
                        <span class="cmt">// We do NOT ACK. The job remains in PEL and will be retried.</span>
                    }
                }
            }
        }
    }
}</pre>
    </div>

    <div class="callout warning">
      <div class="callout-title">Handling Pod Crashes (XAUTOCLAIM)</div>
      <p>If <code>worker-pod-1</code> pulls a job (putting it in PEL) but immediately experiences a hardware failure (OOM kill, power loss), the job will be stuck forever because it was never ACKed. To fix this, a watchdog worker must periodically run <code>XAUTOCLAIM</code> to steal jobs that have been in PEL for more than 10 minutes and re-assign them to healthy pods, guaranteeing exactly-once delivery across a dynamic Kubernetes cluster.</p>
    </div>

</section>"""

with open(filepath, 'r') as f:
    content = f.read()

# Replace the section block for workers
pattern = r'<section class="chapter" id="workers">.*?</section>'
content = re.sub(pattern, new_chapter, content, flags=re.DOTALL)

with open(filepath, 'w') as f:
    f.write(content)

print("Chapter 12 (Workers) expanded successfully.")
